export const WORLD_LANGUAGES = {
  en: { label: 'English', flag: '🇬🇧', code: 'EN' },
  ka: { label: 'Georgian', flag: '🇬🇪', code: 'KA' },
  ru: { label: 'Russian', flag: '🇷🇺', code: 'RU' },
  es: { label: 'Spanish', flag: '🇪🇸', code: 'ES' },
  fr: { label: 'French', flag: '🇫🇷', code: 'FR' },
  de: { label: 'German', flag: '🇩🇪', code: 'DE' },
  it: { label: 'Italian', flag: '🇮🇹', code: 'IT' },
  ar: { label: 'Arabic', flag: '🇱🇧', code: 'AR' },
  zh: { label: 'Chinese', flag: '🇨🇳', code: 'ZH' },
  ja: { label: 'Japanese', flag: '🇯🇵', code: 'JA' },
  ko: { label: 'Korean', flag: '🇰🇷', code: 'KO' },
  pt: { label: 'Portuguese', flag: '🇵🇹', code: 'PT' },
  tr: { label: 'Turkish', flag: '🇹🇷', code: 'TR' },
  hi: { label: 'Hindi', flag: '🇮🇳', code: 'HI' },
  nl: { label: 'Dutch', flag: '🇳🇱', code: 'NL' },
  sv: { label: 'Swedish', flag: '🇸🇪', code: 'SV' },
  pl: { label: 'Polish', flag: '🇵🇱', code: 'PL' },
  uk: { label: 'Ukrainian', flag: '🇺🇦', code: 'UK' },
  ro: { label: 'Romanian', flag: '🇷🇴', code: 'RO' },
  vi: { label: 'Vietnamese', flag: '🇻🇳', code: 'VI' },
  el: { label: 'Greek', flag: '🇬🇷', code: 'EL' },
  he: { label: 'Hebrew', flag: '🇮🇱', code: 'HE' },
  fa: { label: 'Persian', flag: '🇮🇷', code: 'FA' },
  th: { label: 'Thai', flag: '🇹🇭', code: 'TH' },
  id: { label: 'Indonesian', flag: '🇮🇩', code: 'ID' },
  ms: { label: 'Malay', flag: '🇲🇾', code: 'MS' },
  cs: { label: 'Czech', flag: '🇨🇿', code: 'CS' },
  da: { label: 'Danish', flag: '🇩🇰', code: 'DA' },
  fi: { label: 'Finnish', flag: '🇫🇮', code: 'FI' },
  hu: { label: 'Hungarian', flag: '🇭🇺', code: 'HU' },
  no: { label: 'Norwegian', flag: '🇳🇴', code: 'NO' },
  sk: { label: 'Slovak', flag: '🇸🇰', code: 'SK' },
  bg: { label: 'Bulgarian', flag: '🇧🇬', code: 'BG' },
  hr: { label: 'Croatian', flag: '🇭🇷', code: 'HR' },
  lt: { label: 'Lithuanian', flag: '🇱🇹', code: 'LT' },
  lv: { label: 'Latvian', flag: '🇱🇻', code: 'LV' },
  sl: { label: 'Slovenian', flag: '🇸🇮', code: 'SL' },
  et: { label: 'Estonian', flag: '🇪🇪', code: 'ET' },
  sr: { label: 'Serbian', flag: '🇷🇸', code: 'SR' },
  hy: { label: 'Armenian', flag: '🇦🇲', code: 'HY' },
  az: { label: 'Azerbaijani', flag: '🇦🇿', code: 'AZ' },
  uz: { label: 'Uzbek', flag: '🇺🇿', code: 'UZ' },
  kk: { label: 'Kazakh', flag: '🇰🇿', code: 'KK' },
};

export const WORLD_COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia & Herzegovina',
  'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Rep',
  'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark',
  'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
  'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
  'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
  'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea North', 'Korea South', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Madagascar', 'Malawi',
  'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco',
  'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
  'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
  'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts & Nevis', 'Saint Lucia', 'Samoa', 'San Marino', 'Sao Tome & Principe',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
  'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
  'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad & Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda',
  'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela',
  'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
];

export const WORLD_CURRENCIES = {
  USD: { sym: '$', name: 'US Dollar' },
  EUR: { sym: '€', name: 'Euro' },
  GBP: { sym: '£', name: 'British Pound' },
  GEL: { sym: '₾', name: 'Georgian Lari' },
  AED: { sym: 'د.إ', name: 'UAE Dirham' },
  CAD: { sym: 'CA$', name: 'Canadian Dollar' },
  AUD: { sym: 'A$', name: 'Australian Dollar' },
  JPY: { sym: '¥', name: 'Japanese Yen' },
  CNY: { sym: '¥', name: 'Chinese Yuan' },
  INR: { sym: '₹', name: 'Indian Rupee' },
  CHF: { sym: 'CHF', name: 'Swiss Franc' },
  SAR: { sym: 'SR', name: 'Saudi Riyal' },
  QAR: { sym: 'QR', name: 'Qatar Riyal' },
  KWD: { sym: 'KD', name: 'Kuwaiti Dinar' },
  BHD: { sym: 'BD', name: 'Bahraini Dinar' },
  OMR: { sym: 'RO', name: 'Omani Rial' },
  TRY: { sym: '₺', name: 'Turkish Lira' },
  RUB: { sym: '₽', name: 'Russian Ruble' },
  LBP: { sym: 'L.L.', name: 'Lebanese Pound' },
  NZD: { sym: 'NZ$', name: 'New Zealand Dollar' },
  SGD: { sym: 'S$', name: 'Singapore Dollar' },
  HKD: { sym: 'HK$', name: 'Hong Kong Dollar' },
  ZAR: { sym: 'R', name: 'South African Rand' },
  MXN: { sym: 'Mex$', name: 'Mexican Peso' },
  BRL: { sym: 'R$', name: 'Brazilian Real' },
  SEK: { sym: 'kr', name: 'Swedish Krona' },
  NOK: { sym: 'kr', name: 'Norwegian Krone' },
  DKK: { sym: 'kr', name: 'Danish Krone' },
  PLN: { sym: 'zł', name: 'Polish Zloty' },
  ILS: { sym: '₪', name: 'Israeli Shekel' },
  THB: { sym: '฿', name: 'Thai Baht' },
  IDR: { sym: 'Rp', name: 'Indonesian Rupiah' },
  MYR: { sym: 'RM', name: 'Malaysian Ringgit' },
  PHP: { sym: '₱', name: 'Philippine Peso' },
  PKR: { sym: '₨', name: 'Pakistani Rupee' },
};
